MarcoFalke,2017-04-14T21:45:10Z,utACK 3fd09cb beside the comment,https://github.com/bitcoin/bitcoin/pull/10197#issuecomment-294242703,294242703,
jnewbery,2017-04-17T13:09:12Z,"@MarcoFalke I've found the error-and-exit behaviour annoying and intrusive since we introduced it. I'm often working on test cases outside a git repository and either want to add a new test case or modify an existing test case and keep a backup in the same directory (my exact setup is that I'm using rsync to copy my git repo into a directory on a VM, and old files don't automatically get deleted w",https://github.com/bitcoin/bitcoin/pull/10197#issuecomment-294482732,294482732,
MarcoFalke,2017-04-17T14:02:26Z,@jnewbery Sounds reasonable.,https://github.com/bitcoin/bitcoin/pull/10197#issuecomment-294491144,294491144,
jnewbery,2017-04-17T14:32:25Z,Addressed @MarcoFalke's nits,https://github.com/bitcoin/bitcoin/pull/10197#issuecomment-294496632,294496632,
Sjors,2018-01-02T13:41:20Z,"If a MacOS user installs `pidof` via Homebrew, `subprocess.check_output([""pidof"", ""bitcoind""])` will return `b''` which isn't `None`. This then causes the ""There is already a bitcoind process running on this system"" to always appear. Not sure if that's worth fixing.",https://github.com/bitcoin/bitcoin/pull/10197#issuecomment-354768563,354768563,
jnewbery,2018-01-02T19:45:22Z,"> Not sure if that's worth fixing.\n\nCertainly! PRs welcome ðŸ™‚ ",https://github.com/bitcoin/bitcoin/pull/10197#issuecomment-354858042,354858042,
MarcoFalke,2017-04-14T21:44:51Z,"I'd prefer to keep this an error, so that a failing travis will quickly tell the author of a new script that it is not being run.",https://github.com/bitcoin/bitcoin/pull/10197#discussion_r111641009,111641009,test/functional/test_runner.py
MarcoFalke,2017-04-17T14:19:04Z,"```py\nexcept (OSError, subprocess.SubprocessError):\n```\n\nshould be enough?",https://github.com/bitcoin/bitcoin/pull/10197#discussion_r111747814,111747814,test/functional/test_runner.py
MarcoFalke,2017-04-17T14:22:16Z,"Maybe make this warning an error on travis?\n\n```py\nif os.getenv('TRAVIS')=='true':\n  # On travis this warning is an error to prevent merging incomplete commits into master\n  sys.exit(1)\n```",https://github.com/bitcoin/bitcoin/pull/10197#discussion_r111748296,111748296,test/functional/test_runner.py
