paveljanik,2017-05-10T09:13:42Z,"Sorry, but I was not able to reproduce the failure on my systems, so I can't provide tested ACK.\n\nOut of 1000 runs, I have got 8 of this only:\n\n```\n2017-05-10 08:58:54.014000 TestFramework (ERROR): Assertion failed\nTraceback (most recent call last):\n  File ""/private/tmp/bitcoin-master/test/functional/test_framework/util.py"", line 281, in start_nodes\n    rpcs.append(start_node(i, di",https://github.com/bitcoin/bitcoin/pull/10376#issuecomment-300423715,300423715,
jnewbery,2017-05-10T13:04:55Z,"@paveljanik - can you try running the test when you have a lot of disk access happening in parallel which could block disk i/o for the node under test. One way to do this is to run in parallel with pruning.py which does a lot of stop/starts (and therefore flushes to disk a lot). You can do that by changing the BASE_SCRIPTS list in test_runner to something like:\n\n```py\nBASE_SCRIPTS= [\n    '",https://github.com/bitcoin/bitcoin/pull/10376#issuecomment-300475471,300475471,
MarcoFalke,2017-05-14T10:57:24Z,utACK 3ba2c08980dddb3c109a144a818f23a9188426c3,https://github.com/bitcoin/bitcoin/pull/10376#issuecomment-301304684,301304684,
sipa,2017-05-14T18:29:58Z,Concept ACK,https://github.com/bitcoin/bitcoin/pull/10376#issuecomment-301330771,301330771,
paveljanik,2017-05-15T14:12:31Z,"I was not able to reproduce, sorry.\n\nBut reading the code, utACK https://github.com/bitcoin/bitcoin/commit/3ba2c08980dddb3c109a144a818f23a9188426c3",https://github.com/bitcoin/bitcoin/pull/10376#issuecomment-301487433,301487433,
