[
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/441783289",
    "html_url": "https://github.com/bitcoin/bitcoin/pull/14812#issuecomment-441783289",
    "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14812",
    "id": 441783289,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MTc4MzI4OQ==",
    "user": {
      "login": "jamesob",
      "id": 73197,
      "node_id": "MDQ6VXNlcjczMTk3",
      "avatar_url": "https://avatars.githubusercontent.com/u/73197?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jamesob",
      "html_url": "https://github.com/jamesob",
      "followers_url": "https://api.github.com/users/jamesob/followers",
      "following_url": "https://api.github.com/users/jamesob/following{/other_user}",
      "gists_url": "https://api.github.com/users/jamesob/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jamesob/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jamesob/subscriptions",
      "organizations_url": "https://api.github.com/users/jamesob/orgs",
      "repos_url": "https://api.github.com/users/jamesob/repos",
      "events_url": "https://api.github.com/users/jamesob/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jamesob/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-26T20:18:52Z",
    "updated_at": "2018-11-26T20:18:52Z",
    "author_association": "MEMBER",
    "body": "Fixes https://github.com/bitcoin/bitcoin/issues/14710",
    "reactions": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/441783289/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/441956107",
    "html_url": "https://github.com/bitcoin/bitcoin/pull/14812#issuecomment-441956107",
    "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14812",
    "id": 441956107,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MTk1NjEwNw==",
    "user": {
      "login": "kallewoof",
      "id": 250224,
      "node_id": "MDQ6VXNlcjI1MDIyNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/250224?u=8aa4d0fd79dff5cf64a98205c78bc1c96b0bf4b6&v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kallewoof",
      "html_url": "https://github.com/kallewoof",
      "followers_url": "https://api.github.com/users/kallewoof/followers",
      "following_url": "https://api.github.com/users/kallewoof/following{/other_user}",
      "gists_url": "https://api.github.com/users/kallewoof/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kallewoof/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kallewoof/subscriptions",
      "organizations_url": "https://api.github.com/users/kallewoof/orgs",
      "repos_url": "https://api.github.com/users/kallewoof/repos",
      "events_url": "https://api.github.com/users/kallewoof/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kallewoof/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-27T07:30:54Z",
    "updated_at": "2018-11-27T07:30:54Z",
    "author_association": "MEMBER",
    "body": "Post-merge (that was quick btw, but I guess ok since it's only tests): I assume error is unrelated?\r\n\r\n```\r\n2018-11-27T07:29:34.685000Z TestFramework (INFO): Initializing test directory /var/folders/b8/znqr8hj918772gfmd875gzgdd3ypz1/T/testzl4oubll\r\n2018-11-27T07:29:35.945000Z TestFramework (INFO): Sending a bunch of large, junk messages to test memory exhaustion. May take a bit...\r\n2018-11-27T07:29:40.680000Z TestFramework (INFO): Waiting for node to drop junk messages.\r\nFatal write error on socket transport\r\nprotocol: <test_framework.mininode.P2PDataStore object at 0x10f38d240>\r\ntransport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>\r\nTraceback (most recent call last):\r\n  File \"/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py\", line 868, in write\r\n    n = self._sock.send(data)\r\nOSError: [Errno 41] Protocol wrong type for socket\r\n2018-11-27T07:29:40.799000Z TestFramework.mininode (WARNING): Connection lost to 127.0.0.1:14387 due to [Errno 41] Protocol wrong type for socket\r\n2018-11-27T07:29:40.899000Z TestFramework (INFO): Sending a message with incorrect size of 2\r\n2018-11-27T07:29:40.956000Z TestFramework.mininode (WARNING): Connection lost to 127.0.0.1:14387 due to [Errno 54] Connection reset by peer\r\n2018-11-27T07:29:41.061000Z TestFramework (INFO): Sending a message with incorrect size of 77\r\n2018-11-27T07:29:41.222000Z TestFramework (INFO): Sending a message with incorrect size of 78\r\n2018-11-27T07:29:41.384000Z TestFramework (INFO): Sending a message with incorrect size of 79\r\n2018-11-27T07:29:41.761000Z TestFramework (INFO): Stopping nodes\r\n2018-11-27T07:29:42.346000Z TestFramework (INFO): Cleaning up /var/folders/b8/znqr8hj918772gfmd875gzgdd3ypz1/T/testzl4oubll on exit\r\n2018-11-27T07:29:42.346000Z TestFramework (INFO): Tests successful\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/441956107/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/441962826",
    "html_url": "https://github.com/bitcoin/bitcoin/pull/14812#issuecomment-441962826",
    "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14812",
    "id": 441962826,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MTk2MjgyNg==",
    "user": {
      "login": "AkioNak",
      "id": 24285095,
      "node_id": "MDQ6VXNlcjI0Mjg1MDk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/24285095?u=3dcb66c44e0fffed38b732359334e07858c48a0e&v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AkioNak",
      "html_url": "https://github.com/AkioNak",
      "followers_url": "https://api.github.com/users/AkioNak/followers",
      "following_url": "https://api.github.com/users/AkioNak/following{/other_user}",
      "gists_url": "https://api.github.com/users/AkioNak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AkioNak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AkioNak/subscriptions",
      "organizations_url": "https://api.github.com/users/AkioNak/orgs",
      "repos_url": "https://api.github.com/users/AkioNak/repos",
      "events_url": "https://api.github.com/users/AkioNak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AkioNak/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-27T08:01:53Z",
    "updated_at": "2018-11-27T08:01:53Z",
    "author_association": "CONTRIBUTOR",
    "body": "I met the error that @kallewoof pointed out above, too.\r\n(macbook pro/macos 10.13.6)\r\n\r\np2p_invalid_messages.py says ```Tests successful```, but test_runner.py judges that it  ```Failed```.\r\n\r\n```\r\n$ ./test/functional/test_runner.py p2p_invalid_messages.py \r\nTemporary test directory at /var/folders/gy/zxy8j2k17yxfpdbs_td03mwjzvzqs2/T/test_runner_\u20bf_\ud83c\udfc3_20181127_164919\r\n1/1 - p2p_invalid_messages.py failed, Duration: 6 s\r\n\r\nstdout:\r\n2018-11-27T07:49:20.102000Z TestFramework (INFO): Initializing test directory /var/folders/gy/zxy8j2k17yxfpdbs_td03mwjzvzqs2/T/test_runner_\u20bf_\ud83c\udfc3_20181127_164919/p2p_invalid_messages_0\r\n2018-11-27T07:49:21.079000Z TestFramework (INFO): Sending a bunch of large, junk messages to test memory exhaustion. May take a bit...\r\n2018-11-27T07:49:24.885000Z TestFramework (INFO): Waiting for node to drop junk messages.\r\n2018-11-27T07:49:24.989000Z TestFramework.mininode (WARNING): Connection lost to 127.0.0.1:11000 due to [Errno 41] Protocol wrong type for socket\r\n2018-11-27T07:49:25.098000Z TestFramework (INFO): Sending a message with incorrect size of 2\r\n2018-11-27T07:49:25.153000Z TestFramework.mininode (WARNING): Connection lost to 127.0.0.1:11000 due to [Errno 54] Connection reset by peer\r\n2018-11-27T07:49:25.258000Z TestFramework (INFO): Sending a message with incorrect size of 77\r\n2018-11-27T07:49:25.314000Z TestFramework.mininode (WARNING): Connection lost to 127.0.0.1:11000 due to [Errno 54] Connection reset by peer\r\n2018-11-27T07:49:25.420000Z TestFramework (INFO): Sending a message with incorrect size of 78\r\n2018-11-27T07:49:25.579000Z TestFramework (INFO): Sending a message with incorrect size of 79\r\n2018-11-27T07:49:25.960000Z TestFramework (INFO): Stopping nodes\r\n2018-11-27T07:49:26.446000Z TestFramework (INFO): Cleaning up /var/folders/gy/zxy8j2k17yxfpdbs_td03mwjzvzqs2/T/test_runner_\u20bf_\ud83c\udfc3_20181127_164919/p2p_invalid_messages_0 on exit\r\n2018-11-27T07:49:26.446000Z TestFramework (INFO): Tests successful\r\n\r\n\r\nstderr:\r\nFatal write error on socket transport\r\nprotocol: <test_framework.mininode.P2PDataStore object at 0x10ae10a58>\r\ntransport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>\r\nTraceback (most recent call last):\r\n  File \"/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py\", line 868, in write\r\n    n = self._sock.send(data)\r\nOSError: [Errno 41] Protocol wrong type for socket\r\n\r\n\r\n\r\nTEST                    | STATUS    | DURATION\r\n\r\np2p_invalid_messages.py | \u2716 Failed  | 6 s\r\n\r\nALL                     | \u2716 Failed  | 6 s (accumulated) \r\nRuntime: 6 s\r\n\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/441962826/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/442147509",
    "html_url": "https://github.com/bitcoin/bitcoin/pull/14812#issuecomment-442147509",
    "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14812",
    "id": 442147509,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MjE0NzUwOQ==",
    "user": {
      "login": "MarcoFalke",
      "id": 6399679,
      "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399679?u=0691974eedcc2ab5366cc1080fb1c030e87244c2&v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarcoFalke",
      "html_url": "https://github.com/MarcoFalke",
      "followers_url": "https://api.github.com/users/MarcoFalke/followers",
      "following_url": "https://api.github.com/users/MarcoFalke/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
      "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
      "repos_url": "https://api.github.com/users/MarcoFalke/repos",
      "events_url": "https://api.github.com/users/MarcoFalke/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-27T17:32:36Z",
    "updated_at": "2018-11-27T17:32:36Z",
    "author_association": "MEMBER",
    "body": "Is that a deterministic failure due to one of the commits in this pull request? I doubt it, since I have seen it before, but please open a new issue about this.",
    "reactions": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/442147509/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/442179013",
    "html_url": "https://github.com/bitcoin/bitcoin/pull/14812#issuecomment-442179013",
    "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14812",
    "id": 442179013,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MjE3OTAxMw==",
    "user": {
      "login": "MarcoFalke",
      "id": 6399679,
      "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399679?u=0691974eedcc2ab5366cc1080fb1c030e87244c2&v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarcoFalke",
      "html_url": "https://github.com/MarcoFalke",
      "followers_url": "https://api.github.com/users/MarcoFalke/followers",
      "following_url": "https://api.github.com/users/MarcoFalke/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
      "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
      "repos_url": "https://api.github.com/users/MarcoFalke/repos",
      "events_url": "https://api.github.com/users/MarcoFalke/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-27T19:07:23Z",
    "updated_at": "2018-11-27T19:07:23Z",
    "author_association": "MEMBER",
    "body": "According to some other reports asyncio has issues with large buffers on macOS...",
    "reactions": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/442179013/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/442284580",
    "html_url": "https://github.com/bitcoin/bitcoin/pull/14812#issuecomment-442284580",
    "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14812",
    "id": 442284580,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MjI4NDU4MA==",
    "user": {
      "login": "kallewoof",
      "id": 250224,
      "node_id": "MDQ6VXNlcjI1MDIyNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/250224?u=8aa4d0fd79dff5cf64a98205c78bc1c96b0bf4b6&v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kallewoof",
      "html_url": "https://github.com/kallewoof",
      "followers_url": "https://api.github.com/users/kallewoof/followers",
      "following_url": "https://api.github.com/users/kallewoof/following{/other_user}",
      "gists_url": "https://api.github.com/users/kallewoof/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kallewoof/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kallewoof/subscriptions",
      "organizations_url": "https://api.github.com/users/kallewoof/orgs",
      "repos_url": "https://api.github.com/users/kallewoof/repos",
      "events_url": "https://api.github.com/users/kallewoof/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kallewoof/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-28T01:34:01Z",
    "updated_at": "2018-11-28T01:34:01Z",
    "author_association": "MEMBER",
    "body": "Yeah this could be an error that would happen if the original error did not (i.e. the situation post-merge).",
    "reactions": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/442284580/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/236418706",
    "pull_request_review_id": 178491147,
    "id": 236418706,
    "node_id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDIzNjQxODcwNg==",
    "diff_hunk": "@@ -66,7 +66,7 @@ def run_test(self):\n         msg_at_size = msg_unrecognized(\"b\" * valid_data_limit)\n         assert len(msg_at_size.serialize()) == msg_limit\n \n-        with node.assert_memory_usage_stable(perc_increase_allowed=0.03):\n+        with node.assert_memory_usage_stable(perc_increase_allowed=0.5):",
    "path": "test/functional/p2p_invalid_messages.py",
    "position": null,
    "original_position": 5,
    "commit_id": "5a1f57646b34e136051b08f295b6a59aa75241d9",
    "original_commit_id": "0cf1632f03cec7ab1f2bfc83315d52ea06c210be",
    "user": {
      "login": "MarcoFalke",
      "id": 6399679,
      "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarcoFalke",
      "html_url": "https://github.com/MarcoFalke",
      "followers_url": "https://api.github.com/users/MarcoFalke/followers",
      "following_url": "https://api.github.com/users/MarcoFalke/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
      "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
      "repos_url": "https://api.github.com/users/MarcoFalke/repos",
      "events_url": "https://api.github.com/users/MarcoFalke/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "Doesn't percent mean it is denominated in hundreds? So maybe rename it at the same time to `increase_allowed`? And maybe require it to be a named arg with `, *, increase_allowed` in the signature?",
    "created_at": "2018-11-26T20:43:30Z",
    "updated_at": "2018-11-26T20:47:38Z",
    "html_url": "https://github.com/bitcoin/bitcoin/pull/14812#discussion_r236418706",
    "pull_request_url": "https://api.github.com/repos/bitcoin/bitcoin/pulls/14812",
    "author_association": "MEMBER",
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/236418706"
      },
      "html": {
        "href": "https://github.com/bitcoin/bitcoin/pull/14812#discussion_r236418706"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/bitcoin/bitcoin/pulls/14812"
      }
    },
    "reactions": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/236418706/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "start_line": null,
    "original_start_line": null,
    "start_side": null,
    "line": null,
    "original_line": 69,
    "side": "RIGHT"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/236420889",
    "pull_request_review_id": 178493776,
    "id": 236420889,
    "node_id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDIzNjQyMDg4OQ==",
    "diff_hunk": "@@ -66,7 +66,7 @@ def run_test(self):\n         msg_at_size = msg_unrecognized(\"b\" * valid_data_limit)\n         assert len(msg_at_size.serialize()) == msg_limit\n \n-        with node.assert_memory_usage_stable(perc_increase_allowed=0.03):\n+        with node.assert_memory_usage_stable(perc_increase_allowed=0.5):",
    "path": "test/functional/p2p_invalid_messages.py",
    "position": null,
    "original_position": 5,
    "commit_id": "5a1f57646b34e136051b08f295b6a59aa75241d9",
    "original_commit_id": "0cf1632f03cec7ab1f2bfc83315d52ea06c210be",
    "user": {
      "login": "jamesob",
      "id": 73197,
      "node_id": "MDQ6VXNlcjczMTk3",
      "avatar_url": "https://avatars.githubusercontent.com/u/73197?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jamesob",
      "html_url": "https://github.com/jamesob",
      "followers_url": "https://api.github.com/users/jamesob/followers",
      "following_url": "https://api.github.com/users/jamesob/following{/other_user}",
      "gists_url": "https://api.github.com/users/jamesob/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jamesob/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jamesob/subscriptions",
      "organizations_url": "https://api.github.com/users/jamesob/orgs",
      "repos_url": "https://api.github.com/users/jamesob/repos",
      "events_url": "https://api.github.com/users/jamesob/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jamesob/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "Good suggestions; added in a subsequent commit.",
    "created_at": "2018-11-26T20:49:54Z",
    "updated_at": "2018-11-26T20:49:54Z",
    "html_url": "https://github.com/bitcoin/bitcoin/pull/14812#discussion_r236420889",
    "pull_request_url": "https://api.github.com/repos/bitcoin/bitcoin/pulls/14812",
    "author_association": "MEMBER",
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/236420889"
      },
      "html": {
        "href": "https://github.com/bitcoin/bitcoin/pull/14812#discussion_r236420889"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/bitcoin/bitcoin/pulls/14812"
      }
    },
    "reactions": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/236420889/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "start_line": null,
    "original_start_line": null,
    "start_side": null,
    "line": null,
    "original_line": 69,
    "side": "RIGHT",
    "in_reply_to_id": 236418706
  }
]