BitcoinPullTester,2013-05-02T17:40:35Z,"Automatic sanity-testing: PASSED, see http://jenkins.bluematt.me/pull-tester/d605bc4cd13716fde9c34d79a01f4ee128f8814f for binaries and test log.\nThis test script verifies pulls every time they are updated. It, however, dies sometimes and fails to test properly.  If you are waiting on a test, please check timestamps to verify that the test.log is moving at http://jenkins.bluematt.me/pull-tester/cu",https://github.com/bitcoin/bitcoin/pull/2606#issuecomment-17352723,17352723,
sipa,2013-05-03T21:10:06Z,"ACK, tested an artificial error in Bitcoin-Qt under valgrind.\n",https://github.com/bitcoin/bitcoin/pull/2606#issuecomment-17418381,17418381,
laanwj,2013-05-04T13:06:00Z,"ACK\n\nBTW I don't remember before that Shutdown() was called when AppInit2 fails, was this changed in init.cpp recently?\n",https://github.com/bitcoin/bitcoin/pull/2606#issuecomment-17432878,17432878,
sipa,2013-05-04T14:42:15Z,@laanwj This commit added that Shutdown() call?\n,https://github.com/bitcoin/bitcoin/pull/2606#issuecomment-17434251,17434251,
laanwj,2013-05-05T08:01:41Z,"@sipa that's not what I meant. When I initially wrote bitcoin-qt I'm pretty sure that Shutdown() was not called (in the bitcoind case, in init.cpp) in case AppInit2() failed. At least I remember checking this. So it must have been added in the meantime.\n",https://github.com/bitcoin/bitcoin/pull/2606#issuecomment-17448203,17448203,
