BitcoinPullTester,2014-09-22T20:47:56Z,"Automatic sanity-testing: PASSED, see http://jenkins.bluematt.me/pull-tester/p4962_09e6bf04981243e2facb27a9c945875d6910a55a/ for binaries and test log.\nThis test script verifies pulls every time they are updated. It, however, dies sometimes and fails to test properly.  If you are waiting on a test, please check timestamps to verify that the test.log is moving at http://jenkins.bluematt.me/pull-te",https://github.com/bitcoin/bitcoin/pull/4962#issuecomment-56440515,56440515,
sipa,2014-09-22T20:48:41Z,utACK\n,https://github.com/bitcoin/bitcoin/pull/4962#issuecomment-56440620,56440620,
theuni,2014-09-22T23:19:06Z,Presumably this would turn what would've been an abort into a logical error. @sipa I guess the Check() inside of Set() is enough to make this fail gracefully if necessary?\n\nMight be worth checking vchData.size() before the Set() to make it more clear.\n,https://github.com/bitcoin/bitcoin/pull/4962#issuecomment-56458077,56458077,
laanwj,2014-09-23T07:17:12Z,"utACK\n\n@theuni yes, the current code makes sure that this is always the case, but this would be a good place to add an assert that vchData.size>=32.\n",https://github.com/bitcoin/bitcoin/pull/4962#issuecomment-56483682,56483682,
laanwj,2014-09-23T09:00:04Z,Merged via 6f3ae9b\n,https://github.com/bitcoin/bitcoin/pull/4962#issuecomment-56492223,56492223,
