gmaxwell,2016-12-06T17:21:28Z,utACK.,https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-265212571,265212571,
MarcoFalke,2016-12-06T18:26:21Z,"Tagged for 0.12 backport because I am able to reproduce on that branch:\n\n```cpp\nbin/bitcoin-0.12.1/bin/bitcoin-qt -regtest -datadir=/tmp \nbitcoin-qt: wallet/wallet.cpp:2107: bool CWallet::CreateTransaction(const std::vector<CRecipient>&, CWalletTx&, CReserveKey&, CAmount&, int&, std::string&, const CCoinControl*, bool): Assertion `ret' failed.\nAborted (core dumped)\n",https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-265230424,265230424,
MarcoFalke,2016-12-06T18:26:34Z,utACK c24a4f5,https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-265230494,265230494,
paveljanik,2016-12-07T10:53:21Z,"ACK https://github.com/bitcoin/bitcoin/commit/c24a4f5981d47d55aa9e4eb40294832a4d38fb80\n\nWhat about new test case (failing in the master, OK here)?\n",https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-265417093,265417093,
MarcoFalke,2016-12-07T11:02:08Z,"Yes, agree with paveljanik, please add the trivial test case somewhere.\n\nOn Wed, Dec 7, 2016 at 11:53 AM, paveljanik <notifications@github.com>\nwrote:\n\n> ACK c24a4f5\n> <https://github.com/bitcoin/bitcoin/commit/c24a4f5981d47d55aa9e4eb40294832a4d38fb80>\n>\n> What about new test case (failing in the master, OK here)?\n>\n> â€”\n> You are receiving this because you commented.\n> Reply to this em",https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-265418855,265418855,
jonasschnelli,2016-12-07T14:21:43Z,Added a commit with a test that ensures the new behaviour. Test will fail on master.,https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-265459047,265459047,
MarcoFalke,2016-12-07T20:59:16Z,utACK 1a6eacbf3b7e3d5941fec1154079bbc4678ce861\n,https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-265571527,265571527,
paveljanik,2016-12-08T07:04:25Z,"Thank you @jonasschnelli.\n\nTested ACK 1a6eacb\n\nFails on master with\n```\nInitializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testyal7ogu7/50231\nMining blocks...\nAssertion failed: (ret), function CreateTransaction, file wallet/wallet.cpp, line 2392.\nUnexpected exception caught during testing: ConnectionRefusedError(61, 'Connection refused')\n```\n\nOK he",https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-265668543,265668543,
gmaxwell,2016-12-10T00:02:50Z,ACK.,https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-266157002,266157002,
sipa,2016-12-10T00:07:59Z,utACK 1a6eacbf3b7e3d5941fec1154079bbc4678ce861,https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-266157759,266157759,
MarcoFalke,2016-12-14T12:07:53Z,"Backports:\n\n* for 0.13 in #9347\n* for 0.12 in #9211",https://github.com/bitcoin/bitcoin/pull/9295#issuecomment-267018237,267018237,
