DrahtBot,2020-06-19 02:31:44,"<!--e57a25ab6845829454e8d69fc972939a-->\n\nThe following sections might be updated with supplementary metadata relevant to reviewers and maintainers.\n\n<!--174a7506f384e20aa4161008e828411d-->\n### Conflicts\nReviewers, this pull request conflicts with the following ones:\n\n* #19335 (wallet: Cleanup and separate BerkeleyDatabase and BerkeleyBatch by achow101)\n* #19334 (wallet: Introduce WalletDa",https://github.com/bitcoin/bitcoin/pull/19324#issuecomment-646400701,646400701,
promag,2020-06-20 10:33:42,"Code review ACK 4693b11a896cd6b18e61bb3cdbfec72f7e0a2d93.\n\nNo strong opinion whether wallet tool info and salvage should verify.",https://github.com/bitcoin/bitcoin/pull/19324#issuecomment-646974593,646974593,
achow101,2020-07-01 16:37:51,"Apparently the python linter on master fails here, so I've pushed a change to fix that.",https://github.com/bitcoin/bitcoin/pull/19324#issuecomment-652526168,652526168,
MarcoFalke,2020-07-02 00:15:46,"re-ACK d8e9ca66d1 only change is test fixup ðŸ¤ž\n\n<details><summary>Show signature and timestamp</summary>\n\nSignature:\n\n```\n-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA512\n\nre-ACK d8e9ca66d1 only change is test fixup ðŸ¤ž\n-----BEGIN PGP SIGNATURE-----\n\niQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p\npUjlKwwAwqUvc8WhUv1aYY1m9LSQcs/3dHt5UFdx7DRoPH2NBB4t2uZfxn/P",https://github.com/bitcoin/bitcoin/pull/19324#issuecomment-652707350,652707350,
MarcoFalke,2020-07-02 16:36:57,@promag or @ryanofsky Mind to re-ACK?,https://github.com/bitcoin/bitcoin/pull/19324#issuecomment-653110574,653110574,
Sjors,2020-07-06 18:12:33,There's a stray `VerifyEnvironment` and `VerifyDatabaseFile` in `walletdb.h`. Maybe fix those in #19325? ,https://github.com/bitcoin/bitcoin/pull/19324#issuecomment-654389079,654389079,
ryanofsky,2020-06-18 21:50:34,"In commit ""walletdb: Combine VerifyDatabaseFile and VerifyEnvironment"" (ae1a9d9ebbe1b53fd245fddd1907ca90fe3a7abe)\n\nThink need to replace `file_path` with `(walletDir / strFile)` here not just `walletDir`",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442521966,442521966,src/wallet/bdb.cpp
ryanofsky,2020-06-18 21:52:49,"In commit ""walletdb: Combine VerifyDatabaseFile and VerifyEnvironment"" (ae1a9d9ebbe1b53fd245fddd1907ca90fe3a7abe)\n\nAssigning null should be redundant after calling reset",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442522858,442522858,src/wallet/wallettool.cpp
ryanofsky,2020-06-18 21:55:30,"In commit ""walletdb: Combine VerifyDatabaseFile and VerifyEnvironment"" (ae1a9d9ebbe1b53fd245fddd1907ca90fe3a7abe)\n\nWould be a change in behavior, but probably more useful to print `walletDir / strFile` than `strFile` here",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442523873,442523873,src/wallet/bdb.cpp
ryanofsky,2020-06-18 22:04:24,"In commit ""walletdb: Combine VerifyDatabaseFile and VerifyEnvironment"" (ae1a9d9ebbe1b53fd245fddd1907ca90fe3a7abe)\n\nIt doesn't seem like there is a point to calling Verify here in `SalvageWallet` when `ExecuteWalletToolFunc` already called it immediately before calling this. It seems like this `SalvageWallet` function could just be dropped and `ExecuteWalletToolFunc` just call `RecoverDatabaseF",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442527386,442527386,src/wallet/wallettool.cpp
ryanofsky,2020-06-18 22:17:33,"In commit ""walletdb: Combine VerifyDatabaseFile and VerifyEnvironment"" (ae1a9d9ebbe1b53fd245fddd1907ca90fe3a7abe)\n\nThere is a change in behavior here for the wallettool ""info"" and ""salvage"" commands. Previously these commands were just seeing if the environment could be opened here and not actually verifying anything (VerifyEnvironment method name was kind of a misnomer). Now ""info"" and ""salva",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442532065,442532065,src/wallet/wallettool.cpp
achow101,2020-06-18 23:54:02,Done,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442560835,442560835,src/wallet/bdb.cpp
achow101,2020-06-18 23:54:08,Done,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442560856,442560856,src/wallet/wallettool.cpp
achow101,2020-06-18 23:54:15,Done,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442560888,442560888,src/wallet/bdb.cpp
achow101,2020-06-18 23:56:24,"Since the database is closed before we reach this function, we need to reopen it before doing the recovery function. We could remove this and only close the database for `info` but that seems a bit like a hack.\n\nMaybe something to think about for a followup.",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442561512,442561512,src/wallet/wallettool.cpp
achow101,2020-06-18 23:57:10,I've added `VerifyNotInUse`. This function is still called by `Verify` so that the behavior of other `Verify` calls here won't change.,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442561702,442561702,src/wallet/wallettool.cpp
MarcoFalke,2020-06-20 11:23:39,"I don't think we use `assert(false)` anywhere, unless it is to specifically silence `-Wreturn-type`. Though, that doesn't seem to be the case here.",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r443123474,443123474,src/wallet/wallet.cpp
ryanofsky,2020-06-23 14:29:33,"In commit ""walletdb: Combine VerifyDatabaseFile and VerifyEnvironment"" (cba81c3272405332cbb2f3b9c6b2c828c1869d16)\n\nWould call this OpenEnvironment and make it private. Earlier suggestion to add a VerifyNotInUse method https://github.com/bitcoin/bitcoin/pull/19324#discussion_r442532065 was to add a new method wallettool could call, not rename this method in a way which I think is misleading abo",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r444268873,444268873,src/wallet/bdb.cpp
ryanofsky,2020-06-23 14:40:55,"In commit ""walletdb: Combine VerifyDatabaseFile and VerifyEnvironment"" (cba81c3272405332cbb2f3b9c6b2c828c1869d16)\n\n> I've added `VerifyNotInUse`. This function is still called by `Verify` so that the behavior of other `Verify` calls here won't change.\n\nI think this open before open code in wallet tool can be dropped entirely. It seems like the only purpose of this is to show an ""Error load",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r444277894,444277894,src/wallet/wallettool.cpp
achow101,2020-06-23 16:04:59,I've dropped this check and added the `env->Open` that `SalvageWallet` needs to `SalvageWallet`.,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r444338499,444338499,src/wallet/wallettool.cpp
achow101,2020-06-23 16:05:36,I've reverted this back to the single `Verify` and dropped this method entirely as its only usage has also been removed.,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r444338919,444338919,src/wallet/bdb.cpp
achow101,2020-06-24 15:34:57,This was a suggestion from a review: https://github.com/bitcoin/bitcoin/pull/18971#discussion_r432987494,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r444985693,444985693,src/wallet/wallet.cpp
MarcoFalke,2020-06-24 17:16:21,"If a function has a return type, but doesn't return anything, then compilation will fail due to `-Wreturn-type` (assuming warnings are errors). In fact the `assert(false)` will turn off `-Wreturn-type` for this function, so this runtime assert is making the code more fragile, harder to analyse and thus review.",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r445049176,445049176,src/wallet/wallet.cpp
achow101,2020-06-24 17:48:12,I've dropped this assert.,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r445067094,445067094,src/wallet/wallet.cpp
MarcoFalke,2020-06-30 22:58:56,"in commit 17924a533346618531ed2c888c6e8fe67bc3851c\n\nThis change seems unrelated. Maybe put it into a preceding commit and explain what it does? I presume it removes a redundant check that is done as part of `LoadWallet`?",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448024869,448024869,src/wallet/wallettool.cpp
MarcoFalke,2020-06-30 22:59:47,"Same commit\n\nThis also seems unrelated. Is it related to the change in `ExecuteWalletToolFunc`?",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448025146,448025146,src/wallet/salvage.cpp
MarcoFalke,2020-06-30 23:06:08,"in commit 17924a533346618531ed2c888c6e8fe67bc3851c:\n\nAny reason to write to stderr when all other failures are written to the debug log? Since this is a pure utility function, I'd prefer if this returned the error string to the caller in the future, so that the caller can decide how to display the error",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448027237,448027237,src/wallet/salvage.cpp
achow101,2020-07-01 16:31:50,Yes.,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448482601,448482601,src/wallet/salvage.cpp
achow101,2020-07-01 16:32:33,How is it unrelated? This function is being removed from `WalletBatch`.,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448482971,448482971,src/wallet/wallettool.cpp
achow101,2020-07-01 16:34:28,It was to largely retain the previous behavior of this error going to stderr. I think that cleaning up this function to return error strings and remove the LogPrintfs in a followup.,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448483978,448483978,src/wallet/salvage.cpp
MarcoFalke,2020-07-02 00:32:22,"I was wrong. VerifyEnvironment is called via `LoadWallet -> LoadWalletInternal -> CWallet::Verify`, which is <strike>different from</strike> (edit: this was wrong) the `LoadWallet` call below.\n\nSo why is it ok to remove this call to `VerifyEnvironment`?",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448684387,448684387,src/wallet/wallettool.cpp
achow101,2020-07-02 00:43:36,"`VerifyEnvironment` would just call `BerkeleyEnvironment::Open`. A couple of other things also call that in their normal operation. In particular, `CWallet::LoadWallet` creates a `WalletBatch` which creates a `BerkeleyBatch` which calls `BerkeleyEnvironment::Open` in its constructor.\n\nIn the cases where we need to open the environment and aren't using the higher level stuff, a direct call to `",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448687191,448687191,src/wallet/wallettool.cpp
MarcoFalke,2020-07-02 12:02:25,"With ""unrelated"" I meant ""can be split up into its own atomic and logical commit without depending on other changes in this pull request"".\n\nSee the following commit on current master, which compiles fine and runs all tests fine as well:\n\n```\n$ git show \ncommit 43d120ec8a7a999a48ba31e2621efec06ca668f6 (HEAD)\nAuthor: MarcoFalke <falke.marco@gmail.com>\nDate:   Thu Jul 2 07:53:05 2020 ",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448951064,448951064,src/wallet/wallettool.cpp
MarcoFalke,2020-07-02 12:02:44,See https://github.com/bitcoin/bitcoin/pull/19324/files#r448951064,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r448951215,448951215,src/wallet/salvage.cpp
achow101,2020-07-02 14:52:47,Maybe if I need to push again.,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r449059785,449059785,src/wallet/wallettool.cpp
ryanofsky,2020-07-06 17:39:10,"In commit ""walletdb: Combine VerifyDatabaseFile and VerifyEnvironment"" (8f1bcf8b7b6e47c05f2e43dd98ec3505b888d8b3)\n\n> Since the database is closed before we reach this function, we need to reopen it before doing the recovery function. We could remove this and only close the database for `info` but that seems a bit like a hack.\n> \n> Maybe something to think about for a followup.\n\nIt seem",https://github.com/bitcoin/bitcoin/pull/19324#discussion_r450379596,450379596,src/wallet/wallettool.cpp
achow101,2020-07-06 17:50:59,Hmm. Seems like there was a rebase error at some point. I'll make a followup that handles this and a few other related suggestions.,https://github.com/bitcoin/bitcoin/pull/19324#discussion_r450385631,450385631,src/wallet/wallettool.cpp
